### ISSUE TITLE
Could not compile webplatform

### ISSUE THREAD

**Issue by rozgo** [tcr/rust-webplatform#2]
➜  rust-webplatform git:(master) ✗ make  
multirust override nightly-2015-03-12
multirust: using existing install for 'nightly-2015-03-12'
multirust: override toolchain for '/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform' set to 'nightly-2015-03-12'
RUST_BACKTRACE=1 ../cargo-build/target/debug/cargo-build --sysroot ../rust-rt-minimal/sysroot/ --target i386-unknown-emscripten --emit em-js --release --verbose --emcc ./emcc
       Fresh libc v0.1.3
   Compiling webplatform v0.3.0 (file:///Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform)
     Running `rustc src/main.rs --crate-name webplatform --crate-type bin -C opt-level=3 --out-dir /Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/i386-unknown-emscripten/release --emit=dep-info,link --target i386-unknown-emscripten -L dependency=/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/i386-unknown-emscripten/release -L dependency=/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/i386-unknown-emscripten/release/deps --extern libc=/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/i386-unknown-emscripten/release/deps/liblibc-d66ff8cdfdc5cbaa.rlib --extern concat_bytes=/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/release/deps/libconcat_bytes-9ac50532a8511801.dylib --extern webplatform=/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/i386-unknown-emscripten/release/libwebplatform.rlib`
       Fresh webplatform_concat_bytes v0.0.1 (file:///Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform)
src/main.rs:24:13: 26:11 error: type mismatch: the type `[closure src/main.rs:24:30: 26:10]` implements the trait `core::ops::FnMut<()>`, but the trait `for<'r> core::ops::FnMut<(webplatform::Event<'r>,)>` is required (expected tuple, found ()) [E0281]
src/main.rs:24      button.on("click", move || {
src/main.rs:25             bodyref2.prop_set_str("bgColor", "blue");
src/main.rs:26         });
src/main.rs:24:13: 26:11 error: type mismatch: the type `[closure src/main.rs:24:30: 26:10]` implements the trait `core::ops::FnMut<()>`, but the trait `for<'r> core::ops::FnMut<(webplatform::Event<'r>,)>` is required (expected tuple, found ()) [E0281]
src/main.rs:24      button.on("click", move || {
src/main.rs:25             bodyref2.prop_set_str("bgColor", "blue");
src/main.rs:26         });
error: aborting due to 2 previous errors
Could not compile `webplatform`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name webplatform --crate-type bin -C opt-level=3 --out-dir /Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/i386-unknown-emscripten/release --target i386-unknown-emscripten -L dependency=/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/i386-unknown-emscripten/release -L dependency=/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/i386-unknown-emscripten/release/deps --extern libc=/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/i386-unknown-emscripten/release/deps/liblibc-d66ff8cdfdc5cbaa.rlib --extern concat_bytes=/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/release/deps/libconcat_bytes-9ac50532a8511801.dylib --extern webplatform=/Users/rozgo/Projects/rust-webplatform-setup/rust-webplatform/target/i386-unknown-emscripten/release/libwebplatform.rlib --emit dep-info,llvm-ir -C lto --sysroot ../rust-rt-minimal/sysroot/` (exit code: 101)
make: **\* [build] Error 101

**Comment by tcr** [comment]
@rozgo The example for `main.rs` is out of date, but thank you for reminding me. TodoMVC is a more fully-featured example but I'll go ahead and fix this one.

Including it as a crate dependency should be good though.
