### ISSUE TITLE
Maintainer Volunteer

### ISSUE THREAD

**Issue by davidhewitt** [tcr/rust-webplatform#21]
Hi,

It seems like Rust could be a cool language for building on the web with the support for emscripten and webassembly that's now so easy to manage using rustup.

I'd like to offer some of my time to help shape that vision; so if you're interested I would like to help maintain and add features to this crate.

Cheers
David

**Comment by Boscop** [comment]
+1

**Comment by davidhewitt** [comment]
I hope to start toying with something over the upcoming Easter weekend. @tcr please let me know if you'd like me to chip in with this crate or if I should start my own!

**Comment by tcr** [comment]
See #22!
