### ISSUE TITLE
Bury the project officially & redirect users to stdweb

### ISSUE THREAD

**Issue by vlad20012** [tcr/rust-webplatform#27]
One day I decided that it is cool to use rust with wasm. Then I looked for what was done in this direction. And found webplatform! And nothing else... No, guys, I really know how to use google! But I could not find anything other than webplatform. So I decided to fork it, to begin with, and then try to provide maintenance. I found like-minded people. Nobody knew about anything except webplatform. And we starter to work. We've set up an automated testing in a real browser, travis CI. It was really hard. Started some API design... And what's next? And next I found that ALL OF THIS HAS DONE ALREADY! [stdweb](https://github.com/koute/stdweb) is the project that is really the "new webplatform" (not a fork) and really the "DOM bindings for rust". There is even [cargo-web](https://github.com/koute/cargo-web) utility, you can just write `cargo web test` to run tests in a web browser! And f***ing nobody know about it! Why is the world so unfair?

It would be very cool if someone write to the README that the project is closed and if someone looks for DOM bindings they can go to [stdweb](https://github.com/koute/stdweb).

**Comment by davidhewitt** [comment]
A group of us actually tried to do similar to you and start working on this project back in May (see #22). We also found out about stdweb then and the momentum fizzled.

I would agree with you that redirecting to stdweb from here would likely be useful and save a lot of googling. Many many articles on rust wasm still point here.

I would think the call is ultimately for @tcr; this project is his work and I think it's up to him if he wants to declare deprecation of this project and official support for stdweb.

**Comment by tcr** [comment]
Oh I'm down. Anyone with contributor access feel free to point the README to `stdweb`!

**Comment by davidhewitt** [comment]
Cool - I'll do later on!

**Comment by vlad20012** [comment]
If someone is interested, there is also a [project](https://github.com/kryptan/webinden) that aims to generate bindings automatically from WEB API spec. (in a very early stage)
