### ISSUE TITLE
setup.sh has other dependencies?

### ISSUE THREAD

**Issue by MarkSwanson** [tcr/rust-webplatform#3]
I'm going by the documentation, but perhaps there are some steps missing?

setup.sh seems to be downloading emsdk, but emsdk is not found?

~/.../rust/webplatform$ sh setup.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27723  100 27723    0     0  93341      0 --:--:-- --:--:-- --:--:-- 93343
emsdk_portable/
emsdk_portable/emscripten-tags.txt
emsdk_portable/emsdk
emsdk_portable/emsdk_env.sh
emsdk_portable/emsdk_manifest.json
emsdk_portable/README.md
setup.sh: 5: setup.sh: ./emsdk: not found
setup.sh: 6: setup.sh: ./emsdk: not found

**Comment by tcr** [comment]
@MarkSwanson, thanks for pointing this out! Just `cd`ing into setup.sh fixes this, which I missed when reorganizing the script. This should now work on master.
